site_name: Documentacion_Proyecto
site_url: https://DanielMarinhoMartinez.github.io/Documentacion_Proyecto/

# docs es donde se encuentran los archivos de entrada (archivos .md y .pdf)
docs_dir: 'docs'

# site es donde se generarán los archivos estáticos
site_dir: 'site'

# Configuración de la navegación
nav:
  - Index: index.md
  - Manual de Usuario: Manual_de_Usuario.md
  - Guía de Referencia: Guia_de_Referencia.md
  - Guía de Instalación: Guia_de_Instalacion.md

theme:
  name: mkdocs
